server:
  port: 10000

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.igen.rhzl.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver              # mysql驱动包
    url: jdbc:sqlserver://192.168.1.12:1433;DatabaseName=gps              # 数据库名称
    username: sa
    password: bl00m2#
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:11000/eureka/
  instance:
    instance-id: rhzl-provider
    prefer-ip-address: true

info:
  app.name: rhzl
  company.name: www.brian.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
